apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: amundsenfrontend
  name: amundsenfrontend
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amundsenfrontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amundsenfrontend
    spec:
      containers:
        - env:
          - name: SEARCHSERVICE_BASE
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: SEARCHSERVICE_BASE
          - name: METADATASERVICE_BASE
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: METADATASERVICE_BASE
          name: amundsenfrontend
          image: {{ required "Missing value AMUNDSEN_FRONTEND_IMAGE_NAME" .Values.AMUNDSEN_FRONTEND_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: {{ required "Missing value AMUNDSEN_FRONTEND_MEMORY" .Values.AMUNDSEN_FRONTEND_MEMORY | quote }}
      restartPolicy: Always
status: {}
