apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: es-amundsen-atlas
  name: es-amundsen-atlas
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-amundsen-atlas
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: es-amundsen-atlas
    spec:
      initContainers:
        - name: increase-the-vm-max-map-count
          image: {{ required "Missing value ES_BUSY_IMAGE" .Values.ES_BUSY_IMAGE }}
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
#        - name: increase-ulimits
#          image: {{ required "Missing value ES_BUSY_IMAGE" .Values.ES_BUSY_IMAGE }}
#          command:
#            - sysctl
#            - fd.file-max=65536
#          securityContext:
#            privileged: true
        - name: fix-rights
          image: {{ required "Missing value ES_BUSY_IMAGE" .Values.ES_BUSY_IMAGE }}
          command:
            - /bin/chmod
            - "777"
            - /usr/share/elasticsearch/data
          volumeMounts:
          - name: es-amundsen-atlas-claim0
            mountPath: "/usr/share/elasticsearch/data"
          securityContext:
            privileged: true
      containers:
      - env:
        - name: cluster.name
          value: {{ required "Missing value ES_CLUSTERNAME" .Values.ES_CLUSTERNAME }}
        - name: xpack.security.enabled
          value: {{ required "Missing value ES_SECURITY"  .Values.ES_SECURITY | quote }}
#        - name: cluster.initial_master_nodes
#          valueFrom:
#            fieldRef:
#              apiVersion: v1
#              fieldPath: metadata.name
        image: {{ required "Missing value ES_IMAGE" .Values.ES_IMAGE }}
        imagePullPolicy: Always
        name: es-amundsen-atlas
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          requests:
            memory: {{ required "Missing value ES_MEMORY" .Values.ES_MEMORY | quote }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-amundsen-atlas-claim0
      restartPolicy: Always
      volumes:
      - name: es-amundsen-atlas-claim0
        persistentVolumeClaim:
          claimName: es-amundsen-atlas-claim0
status: {}
