apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: atlas
  name: atlas
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: atlas
    spec:
      hostname: atlas
      containers:
        - env:
          - name: ATLAS_KICKSTART_AMUNDSEN
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: ATLAS_KICKSTART_AMUNDSEN
          - name: ATLAS_HOST
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: PROXY_HOST
          - name: ATLAS_PORT
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: PROXY_PORT
          - name: ATLAS_USERNAME
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: CREDENTIALS_PROXY_USER
          - name: ATLAS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: CREDENTIALS_PROXY_PASSWORD
          name: atlas
          image: {{ required "Missing value ATLAS_IMAGE_NAME" .Values.ATLAS_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 21000
          resources:
            requests:
              memory: {{ required "Missing value ATLAS_MEMORY" .Values.ATLAS_MEMORY | quote }}
      restartPolicy: Always
status: {}
