apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: atlas
  name: atlas
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "21000"
    port: 21000
    targetPort: 21000
  - name: "8080"
    port: 8080
    targetPort: 21000
  selector:
    app: atlas
status:
  loadBalancer: {}