apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: amundsensearch
  name: amundsensearch
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amundsensearch
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amundsensearch
    spec:
      containers:
        - env:
          - name: PROXY_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: PROXY_ENDPOINT
          - name: CREDENTIALS_PROXY_USER
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: CREDENTIALS_PROXY_USER
          - name: CREDENTIALS_PROXY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: CREDENTIALS_PROXY_PASSWORD
          - name: PROXY_PORT
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: ELASTIC_PORT
          - name: PROXY_CLIENT
            valueFrom:
              secretKeyRef:
                name: poc-oss-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: ELASTIC_CLIENT
          name: amundsensearch
          image: {{ required "Missing value AMUNDSEN_SEARCH_IMAGE_NAME" .Values.AMUNDSEN_SEARCH_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: {{ required "Missing value AMUNDSEN_SEARCH_MEMORY" .Values.AMUNDSEN_SEARCH_MEMORY | quote }}
      restartPolicy: Always
status: {}
