apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: amundsensearch
  name: amundsensearch
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    app: amundsensearch
status:
  loadBalancer: {}