apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poc-nginx
  name: poc-nginx
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poc-nginx
    spec:
      containers:
        - image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
          imagePullPolicy: Always
          name: poc-nginx
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ required "Missing value POC_NGINX_MEMORY" .Values.POC_NGINX_MEMORY | quote }}
      restartPolicy: Always
status: {}