apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poc-nginx
  name: poc-nginx
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: poc-nginx
status:
  loadBalancer: {}