apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: amundsenmetadata
  name: amundsenmetadata
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
  selector:
    app: amundsenmetadata
status:
  loadBalancer: {}