#namespace
NAMESPACE: staging

#amundsen_metadata
AMUNDSEN_METADATA_IMAGE_NAME: amundsendev/amundsen-metadata:latest
PROXY_HOST: atlas
PROXY_PORT: 21000
PROXY_ENCRYPTED: "False"
PROXY_CLIENT: ATLAS
METADATA_SVC_CONFIG_MODULE_CLASS: metadata_service.config.AtlasConfig
AUNDSEN_METADATA_MEMORY: "1000Mi"