apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: amundsenfrontend
  name: amundsenfrontend
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "8080"
    port: 8080
    targetPort: 5000
  selector:
    app: amundsenfrontend
status:
  loadBalancer: {}